#!/bin/bash
#
# Shell script to test the top-level landing (help) script from inside the QMTools Docker container.
# This script mounts the required directories and call the  inside the container.
#
# echo "ARGS=$*"

PROG=$0

export SIF=${SIF:-/contrib/singularity/shared/neuroimaging}
TSTIMG=qmtools_test.sif

apptainer exec --pwd / ${SIF}/${TSTIMG} qmtools $@
